name: Build and Deploy

on:
  push:
    branches:
      - main # 更改为主分支名称，例如：master 或者 develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # 更改为所需的运行器环境

    env:
      API_KEY: ${{ secrets.API_KEY }} # 使用 GitHub Secrets

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # 添加任何必要的构建步骤，例如安装依赖项、编译代码等
